# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0002_auto_20161114_1559'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectsApp', '0002_auto_20161114_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
    ]
