# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_auto_20161208_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='PLRequirements',
            field=models.ManyToManyField(blank=True, to='ProjectsApp.PLRequired'),
        ),
        migrations.AddField(
            model_name='project',
            name='SpecialityRequirements',
            field=models.ManyToManyField(blank=True, to='ProjectsApp.Speciality'),
        ),
        migrations.AddField(
            model_name='project',
            name='YoERequirements',
            field=models.ManyToManyField(blank=True, to='ProjectsApp.YoERequired'),
        ),
    ]
