# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0006_auto_20161208_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='PLRequirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='SpecialityRequirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='YoERequirements',
        ),
        migrations.AddField(
            model_name='project',
            name='PLRequirement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.PLRequired'),
        ),
        migrations.AddField(
            model_name='project',
            name='SpecialityRequirement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Speciality'),
        ),
        migrations.AddField(
            model_name='project',
            name='YoERequirement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.YoERequired'),
        ),
    ]
