# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0007_auto_20161208_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='PLRequirement',
        ),
        migrations.AddField(
            model_name='project',
            name='PLRequirement',
            field=models.ManyToManyField(blank=True, null=True, to='ProjectsApp.PLRequired'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='SpecialityRequirement',
        ),
        migrations.AddField(
            model_name='project',
            name='SpecialityRequirement',
            field=models.ManyToManyField(blank=True, null=True, to='ProjectsApp.Speciality'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='YoERequirement',
        ),
        migrations.AddField(
            model_name='project',
            name='YoERequirement',
            field=models.ManyToManyField(blank=True, null=True, to='ProjectsApp.YoERequired'),
        ),
    ]
