# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0008_auto_20161208_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='r1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='r2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='r3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='PLRequirement',
            field=models.ManyToManyField(blank=True, to='ProjectsApp.PLRequired'),
        ),
        migrations.AlterField(
            model_name='project',
            name='SpecialityRequirement',
            field=models.ManyToManyField(blank=True, to='ProjectsApp.Speciality'),
        ),
        migrations.AlterField(
            model_name='project',
            name='YoERequirement',
            field=models.ManyToManyField(blank=True, to='ProjectsApp.YoERequired'),
        ),
    ]
