# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0009_auto_20161208_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='PLRequirement',
        ),
        migrations.AddField(
            model_name='project',
            name='PLRequirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectsApp.PLRequired'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='SpecialityRequirement',
        ),
        migrations.AddField(
            model_name='project',
            name='SpecialityRequirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectsApp.Speciality'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='YoERequirement',
        ),
        migrations.AddField(
            model_name='project',
            name='YoERequirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectsApp.YoERequired'),
        ),
    ]
