# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0011_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
