# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_auto_20161202_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='about',
        ),
        migrations.AddField(
            model_name='engineer',
            name='alma_mater',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
