# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_auto_20161206_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
