# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_auto_20161207_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
