# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_auto_20161208_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bookmarks',
        ),
        migrations.DeleteModel(
            name='BookMark',
        ),
    ]
