# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0005_auto_20161114_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
