# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0006_course_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
